### ISSUE TITLE
wav duration

### ISSUE THREAD

**Issue by zhangshengnan96** [Sato-Kunihiko/audio-SNR#14]
Hello, I wonder the duration of the source file and the noise file need to be same or could be totally different, if the duration of nosie file is shorter than the source file, could the source file be filled with noise.

**Comment by Sato-Kunihiko** [comment]
@zhangshengnan96 
Hello.
The scripts accept the files if the duration of the noise file is longer than that of the source file.
If the duration of the noise file is shorter than that of the source file, the scripts fail.

Do you want to use the noise file which has a shorter duration than the source file?

**Comment by zhangshengnan96** [comment]
yes, maybe the duration of noise file is shorter than the source file.

**Comment by Sato-Kunihiko** [comment]
I got it. 
You can submit a pull request for using the shorter noise file. What do you think?

**Comment by zhangshengnan96** [comment]
> I got it. You can submit a pull request for using the shorter noise file. What do you think?

ok, thanks a lot. Have a good day.
